import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";

const pixelFont = localfont({
  src: [
    {
      path: "../../public/fonts/fusion-pixel.woff2",
    },
  ],
  variable: "--font-pixel",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pixelFont.variable} antialiased`}>{children}</body>
    </html>
  );
}
